apiVersion: autoscaling/v2
kind: {{ .Values.HorizontalPodscalar.kind}}
metadata:
  name: {{ .Values.HorizontalPodscalar.metadata.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.HorizontalPodscalar.spec.scaleTargetRef.kind}}
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

  