apiVersion: autoscaling/v2
kind: {{ .Values.horizontalPodAutoscaler.kind}}
metadata:
  name: {{ .Values.horizontalPodAutoscaler.metadata.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.horizontalPodAutoscaler.spec.scaleTargetRef.kind}}
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

  