apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-upload-app
  template:
    metadata:
      labels:
        app: file-upload-app
    spec:
      containers:
      - name: file-upload-app
        image: nitesh287/my-file-upload-bucket:v2
        ports:
        - containerPort: 8080