apiVersion: apps/v1
kind: {{ .Values.kind}}
metadata:
  name: {{ .Values.metadata.name}}
  labels:
    app: {{ .Values.metadata.labels.app}}
spec:
  replicas: {{ .Values.spec.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app}}
    spec:
      containers:
      - name: {{ index .Values.spec.containers 0 "name"}}
        image: {{ index .Values.spec.containers 0 "image"}}
        port:
        - containerPort: {{ index .Values.spec.containers 0 "port"}}