replicaCount: 2

image:
  repository: ankitthedevops/myimage
  tag: ef4de47
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service