replicaCount: 2

image:
  repository: ankitthedevops/myimage
  tag: "12598746622"
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service