apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: ankitthedevops/app
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ankitthedevops/app:latest