apiVersion: apps/v1
kind: {{ .Values.kind}}
metadata:
  name: {{ .Values.metadata.name}}
spec:
  replicas: {{ .Values.spec.replicas}}
  template: 
    spec:
      containers:
      - name: {{ index .Values.spec.containers 0 "name"}}
        image: {{ index .Values.spec.containers 0 "image"}}