name: Docker Image Vulnerability Scanning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  vulnerability-scanning:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASS }}

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker build -t ${{ secrets.DOCKERPASS }}/simple_python_app:v1 ./simple_python_app/ || {
            echo "Docker build failed. Exiting.";
            exit 1;
          }

      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKERUSER }}/simple_python_app:v1
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Push Docker Image
        run: |
          echo "Pushing Docker Image..."
          docker push ${{ vers.DOCKERNAME }}/simple_python_app:v1 || {
            echo "Docker push failed. Exiting.";
            exit 1;
          }
          echo "Image pushed successfully."
