name: Workflow to build the image and Deploy the application

on:
  pull_request:
    types: 
      - closed
    paths:
      - 'simple_python_app/**'
   
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Buld the image
      run: |
       COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
       docker build -t ${{ vars.DOCKERUSER}}/myimage:${COMMIT_SHA} simple_python_app/
       docker images

    - name: Push image to Dockerhub
      run: |
       COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
       docker push ${{ vars.DOCKERUSER}}/myimage:${COMMIT_SHA}
 
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    needs: build-and-push
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHA_TOKEN }}
    - name: Update tag in Helm chart
      run: |
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        sed -i "s/tag: .*/tag: ${COMMIT_SHA}/" helm_gke_deployment/simple-deployment/values.yaml

    - name: Create a new branch
      run: |
        BRANCH_NAME="update-helm-tag-${{ github.sha }}"
        git config --global user.email "ankitsingh.devops@gmail.com"
        git config --global user.name "ankitthedevops"
        git checkout -b $BRANCH_NAME
        git add helm_gke_deployment/simple-deployment/values.yaml
        git commit -m "Update tag in Helm chart to ${COMMIT_SHA}"
        git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD) --no-verify

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Update Helm chart tag to $COMMIT_SHA"
        body: "This PR updates the Helm chart tag to the new commit SHA: $COMMIT_SHA."
        base: main
        branch: update-helm-tag-${{ github.sha }}
        token: ${{ secrets.GHA_TOKEN }}
        branch-suffix: timestamp
